### PR TITLE
Fixes for string and array data types

### LINKED ISSUE #7: String datatype not supported by transpiler
Using `String` datatype as function inputs, results in the `poseidon` compiler throwing an error.

`Error: An error occurred while formatting the source code: expected ','`

Reference code: https://github.com/arihantbansal/program-examples/tree/poseidon-account-data/basics/account-data/poseidon 

This issue is blocking TypeScript program updates for https://github.com/solana-developers/program-examples

### LINKED ISSUE #10: Uint8Array and related types not compiling correctly
Types such as `Uint8Array` in TS should get compiled down to `Vec<u8>` type. This seems to work when it is a type of parameter in function definitions, but not when used as a field type for accounts.

 Reference code: https://github.com/arihantbansal/program-examples/tree/poseidon-account-data/basics/account-data/poseidon

### PR DESCRIPTION
**Pull request by mwaa**
Adds Support for string and array data types

- New function `struct_rs_type_from_str` in ts_types.rs to build rust token stream from string value
- For existing function `rs_type_from_str` add a comma punctuation to correct token stream for class params
- New function `extract_of_type` that matches type of typescript data types between TsTypeRef e.g u8, TsKeywordType e.g string and TsArrayType e.g string[]
- Simple conversion of TsArrayType string[] to Vec<String>
- In ts_types.rs a new array type for string arrays

Reference Code
- https://github.com/mwaa/program-examples/tree/add-basics-favorites-poseidon/basics/favorites/poseidon

Please note functionality
- Currently expects using `string[]` an improvement could be to support `Array<String>` which falls under TsTypeRef
- Space added a big value of 100 for other data types an improvement could be to use the macro InitSpace or explicit access on setting space value

Closes #10 
Closes #7

### CODE REVIEW

**Comment by mwaa** [comment]
@ShrinathNR please help in reviewing.
My rust code isn't the best and looking forward to your guidance on next steps in getting this accepted.

**Comment by ShrinathNR** [comment]
There are few issues with this approach,

- its better to avoid types like string/String type from typescript to avoid string lib compatibility issues and use our own type like how we implemented Numeric types to avoid compatibility issues with math lib

- don't default to any types as it creates undefined behavior for devs, better to be explicit. eg: extract_kind_str defaults to u8, extract_of_type defaults to String type and finally for space +100. better to have some argument asking devs.

I am planning to implement string type considering the above. What do you think? Lemme know if you have any other simpler way.

**Comment by mwaa** [comment]
- Yes it makes sense to implement a String type to avoid compatibility and inconsistency issues. Let me know once the String Type is available and can change the PR accordingly
- For defaults yes it makes sense for the dev to explicitly choose what they would like. Let me look into that. Does it make sense to pass the defaults via the CLI or via a config file. If you for see more points control then file would be best but just for space and data type the two can be passed via CLI

Let me know what you think

**Comment by ShrinathNR** [comment]
I see that you changed it to return Result and avoided default types, appreciate it. I will review your commit, add String & Vec type support and merge this.

**Comment by mwaa** [comment]
Yes the idea was if the type is not implemented just notify the dev with an error message

**Comment by ShrinathNR** [comment]
I have added String and Array of other types, removed matches for TS based keywords, removed redundancy of rs_type_from_str & struct_rs_type_from_str. Now the only problem is space calculation. I have tried creating FixedLengthArray type and other ways but it messes with the types in the instructions, thought i would make the file self contained but doesn't seem to work. I guess, I have to get types' length at runtime in CLI like you say.

**Comment by ShrinathNR** [comment]
@deanmlittle what do you think about this approach?
CLI input
poseidon_output4
Account struct
poseidon_output3
poseidon_output2

**Comment by mwaa** [comment]
@ShrinathNR Nice work.

Am exploring the instructions approach and parsing the string arguments to the instructions macro then adding input.len()
Something similar to below. Let me know if i should proceed with it for otherwise the CLI approach is good and gives more control to the dev.

```
#[derive(Accounts)]
#[instruction(message: String)]
pub struct SetMessageContext<'info> {
    #[account(
        init,
        payer = payer,
        space = 4 + message.len(),
        seeds = [b"message",
        payer.key().as_ref()],
        bump,
    )]
    pub message: Account<'info, Favorites>,
    #[account(mut)]
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,
}
```

**Comment by ShrinathNR** [comment]
using ix arguments in account struct already works for few cases. but using that to define space constraint would be restrictive to make devs pass it as instruction attribute just to add it to space especially considering all Vec types, the transpiled anchor would be weird if the account has too many properties. Its better to infer from the types defined in the interface and through CLI imo.

**Comment by mwaa** [comment]
@ShrinathNR 
- Yes its better to give more control via the CLI to the devs
- Tested out the changes then added an additional prompt for Vec<String> to capture the average length of values for the strings
-  Also added a link for anchor space reference

Screenshot 2024-10-27 at 11 42 33

**Comment by ShrinathNR** [comment]
hey, i figured out a way to have these type info in the file itself without using CLI, it also lets us to write methods for these types in future. I will commit it here.
Account:
poseidon_output6
tranpiled anchor:
image

**Comment by Memewtoo** [comment]
The latest commit was successful in supporting `String` types for accounts, but when used as a function input, anything more than one `String` input would return the error `Error: An error occurred while formatting the source code: expected `, which is the same as issue #7.

code for reference:
```RUST
export default class AccountData {
    static PROGRAM_ID = new Pubkey("11111111111111111111111111111111");

    createAccountInfo(
        payer: Signer,
        account_info: AccountInfoState,
        some_string: String<10>,
        some_another_string: String<10>,
    ): Result {
        account_info.derive([payer.key]).init();

        account_info.some_string = some_string;
        account_info.some_another_string = some_another_string;
    }
}

export interface AccountInfoState extends Account{
    some_string: String<10>,
    some_another_string: String<10>,
}
```

**Comment by ShrinathNR** [comment]
hey, it works fine for me, make sure you're using the master branch latest commit.
Poseidon program:
image
Transpiled anchor:
image

**Pull request merged**
