### PR TITLE
Added createAccount SystemProgram method 

### PR DESCRIPTION
**Pull request by adpthegreat**
I added this function to create a system Account but I'm having a challenge 

I generate the code using the quote!{} macro correctly , but the problem I have is that in the generated code 

```rust 
use anchor_lang::prelude::*;
use anchor_lang::system_program::{CreateAccount, create_account};
declare_id!("AaT7xduNcfZGNvpCCmggamiECjTv8nGAdWAZUNXq6Ve");
#[program]
pub mod rent_program {
    use super::*;
    pub fn create_system_account(
        ctx: Context<CreateSystemAccountContext>,
        account_data: AddressData,
    ) -> Result<()> {
        let account_span = (account_data.try_to_vec()?).len();
        let lamports_required = (Rent::get()?).minimum_balance(account_span);
        let cpi_ctx = CpiContext::new(
            ctx.accounts.system_program.to_account_info(),
            CreateAccount {
                from: ctx.accounts.payer.to_account_info(),
                to: ctx.accounts.new_account.to_account_info(),
            },
        );
        create_account(
            cpi_ctx,
            lamports_required,
            account_span as u64,
            &ctx.accounts.system_program.key(),
        )?;
        Ok(())
    }
}
#[derive(Accounts)]
pub struct CreateSystemAccountContext<'info> {
    #[account()]
    pub account_data: Account<'info, AddressData>,
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(mut)]
    pub new_account: Signer<'info>,
    pub system_program: Program<'info, System>,
}
#[account]
pub struct AddressData {
    pub name: String,
    pub address: String,
}

```

this line 
```rust    
 #[account()]
   pub account_data: Account<'info, AddressData>,
```
is not supposed to there , as we're creating a new account using the address data it would be contradictory to include is as part of the accounts we are declaring in the struct , and it also makes testing impossible, so I need help with implementing the logic so that it would not be included as part of the accounts when we're trying to create a new account @ShrinathNR

### CODE REVIEW

**Comment by ShrinathNR** [comment]
hey, can you share the poseidon TS program that you used to generate this anchor program

**Comment by adpthegreat** [comment]
yeah sure
``` typescript 

import { Account, Pubkey, Result, Signer, SystemProgram, u8, u64 ,String} from '@solanaturbine/poseidon';

export default class RentProgram {
  static PROGRAM_ID = new Pubkey('AaT7xduNcfZGNvpCCmggamiECjTv8nGAdWAZUNXq6Ve');

  // the point of passing address data is to get the accounts size to determine the necessary minimum rent 
  //Create a new system account

  createSystemAccount(payer: Signer, new_account: Signer, account_data:AddressData): Result {
    SystemProgram.createAccount(
      payer, // from 
      new_account, // to
      account_data // acct_data (we pass it in so that we can get the right type )
    )
  }
}

export interface AddressData extends Account {
  name: String<20>;
  address: String<20>;
}

```

**Comment by adpthegreat** [comment]
https://github.com/Turbin3/poseidon-types/pull/1 and this is the corresponding type signature

**Comment by adpthegreat** [comment]
any updates on this @ShrinathNR ?

**Comment by ShrinathNR** [comment]
hey, Thanks for sharing the Poseidon program above. I have been busy with initialize mint feature and formatting of transpiled anchor. I will definitely take a look at it and help you merge this. DW

**Comment by adpthegreat** [comment]
Alright, thank you

**Comment by ShrinathNR** [comment]
hey, really appreciate your patience. there are few issues with the approach. 
- accounts needs to be passed in the account struct to be used for create_account
-  and there multiple ways to find the size parameter, either by directly passing a value or creating the data there and using its vec len or implementing a LEN const for the struct.

I am planning to implement the create_account ix considering the above. What do you think? Lemme know if you have any other simpler way.

**Comment by adpthegreat** [comment]
That'll be great , i don't have any better ideas tbh i was trying to make sure it works, even writing it felt hacky but yeah, i'll leave it to you , thank you very much.

**Comment by ShrinathNR** [comment]
Ok then, I will close this PR. 
Thanks, I will add support for this in the upcoming commits.

**Comment by adpthegreat** [comment]
Alright thanks looking forward to it

**Pull request closed without merging**
